# Generated by Django 2.2.3 on 2019-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=30)),
                ('heroine', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('genre', models.CharField(help_text='Seperate genre with spaces', max_length=150, null=True)),
                ('language', models.CharField(help_text='Seperate language with spaces', max_length=150, null=True)),
                ('release_date', models.DateField(help_text='mm/dd/yyyy')),
                ('runtime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatrename', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
