# Generated by Django 2.2.3 on 2019-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='movie',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
