# Generated by Django 2.2.3 on 2019-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0003_theatre_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('screen', models.CharField(max_length=30)),
                ('theatre', models.CharField(max_length=30)),
                ('movie', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
