# Generated by Django 2.2.3 on 2019-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0009_auto_20190809_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='select_seat',
            field=models.CharField(choices=[('₹100', (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'))), ('₹70', (('F', 'F'), ('G', 'F'), ('H', 'H')))], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticketprice',
            field=models.CharField(choices=[('₹100', '₹100'), ('₹70', '₹70')], max_length=30),
        ),
    ]
