# Generated by Django 2.2.3 on 2019-08-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0011_auto_20190813_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='theatre',
            field=models.CharField(choices=[('pvr forummall', 'pvr forummall'), ('br hitech', 'br hitech'), ('cine polis JNTU', 'cine polis JNTU'), ('big movies AMPT', 'big movies AMPT')], max_length=30),
        ),
    ]
