# Generated by Django 2.2.3 on 2019-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0012_auto_20190813_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.CharField(choices=[('Ranarangam', 'Ranarangam'), ('Evaru', 'Evaru'), ('Kobbari matta', 'Kobbari matta'), ('Manmadhudu 2', 'Manmadhudu 2')], max_length=30),
        ),
    ]
