# Generated by Django 2.2.3 on 2019-08-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0013_auto_20190813_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(help_text='dd/mm/yyyy'),
        ),
    ]
