# Generated by Django 2.2.3 on 2019-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0014_auto_20190813_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(help_text='mm/dd/yyyy'),
        ),
    ]
