# Generated by Django 2.2.3 on 2019-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0015_auto_20190814_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='mm/dd/yyyy'),
        ),
    ]
